workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Skip pipeline for tags
    - if: $CI_COMMIT_BRANCH
      when: always # Run pipeline for all branches

stages:
  - bootstrap
  - code:release

variables:
  CHORE_BOOTSTRAP: '/chore!: bootstrap/'

bootstrap:
  image: alpine:latest
  stage: bootstrap
  before_script:
    - apk add --no-cache bash curl jq
  script:
    - chmod +x $CI_PROJECT_DIR/scripts/bootstrap-github.sh
    - $CI_PROJECT_DIR/scripts/bootstrap-github.sh
  # Triggers only from main with the key word bootstrap
  rules:
    - if:
        '$CI_COMMIT_MESSAGE =~ $CHORE_BOOTSTRAP && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

code:release:
  stage: code:release
  image: node:lts
  variables:
    GL_TOKEN: ${RELEASE_BOT_ACCESS_TOKEN}
  before_script:
    - |
      npm i -g \
      semantic-release@24.0.0 \
      @semantic-release/commit-analyzer \
      @semantic-release/release-notes-generator \
      @semantic-release/changelog \
      @semantic-release/git \
      conventional-changelog-conventionalcommits
  script:
    - npx semantic-release --ci
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
